language: ruby
rvm: 2.2.7
sudo: false
matrix:
  include:
    - rvm: 2.3.6
    - rvm: 2.4.2
    - rvm: 2.5.0
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

before_install:
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
